import type { Express } from "express";
import { type Server } from "http";
import { registerAuthRoutes } from "./auth";
import { registerSuperRoutes } from "./super";
import { registerTenantRoutes } from "./tenant";
import { registerOrderRoutes } from "./orders";
import { registerBranchRoutes } from "./branches";
import { registerCashRoutes } from "./cash";
import { registerProductRoutes } from "./products";
import { registerSttRoutes } from "./stt";
import { registerTrackingRoutes } from "./tracking";
import { registerDeliveryRoutes } from "./delivery";
import { registerBranchUserRoutes } from "./branch-users";
import { registerStaticUploads, registerUploadRoutes } from "./uploads";
import { registerExpenseRoutes } from "./expenses";
import { registerBrandingRoutes } from "./branding";
import { registerPdfRoutes } from "./pdfs";
import { registerAuditRoutes } from "./audit";
import { registerReportRoutes } from "./reports";
import { registerMessageTemplateRoutes } from "./message-templates";
import { registerSaleRoutes } from "./sales";
import { registerCashierRoutes } from "./cashiers";
import { registerImportRoutes } from "./imports";
import { registerStatusRoutes } from "./statuses";
import { registerStockRoutes } from "./stock";

export async function registerRoutes(httpServer: Server, app: Express): Promise<Server> {
  app.get("/health", (_req, res) => {
    res.status(200).json({ ok: true });
  });
  registerStaticUploads(app);
  registerUploadRoutes(app);
  registerAuthRoutes(app);
  registerSuperRoutes(app);
  registerTenantRoutes(app);
  registerBrandingRoutes(app);
  registerPdfRoutes(app);
  registerAuditRoutes(app);
  registerOrderRoutes(app);
  registerBranchRoutes(app);
  registerCashRoutes(app);
  registerProductRoutes(app);
  registerSttRoutes(app);
  registerTrackingRoutes(app);
  registerDeliveryRoutes(app);
  registerBranchUserRoutes(app);
  registerExpenseRoutes(app);
  registerReportRoutes(app);
  registerMessageTemplateRoutes(app);
  registerSaleRoutes(app);
  registerCashierRoutes(app);
  registerImportRoutes(app);
  registerStatusRoutes(app);
  registerStockRoutes(app);
  return httpServer;
}
